### ISSUE TITLE
Included test.py does not work

### ISSUE THREAD

**Issue by mkierc** [J-CITY/tinyWinToast#1]
Trying to run `tinyWinToast/test/test.py` results in:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    toast = Toast()
NameError: name 'Toast' is not defined
```

on Python 3.6.8 & 3.7.2

and:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import tinyWinToast.tinyWinToast
  File "C:\Python27\lib\site-packages\tinyWinToast\tinyWinToast.py", line 677, in <module>
    toast.show()
  File "C:\Python27\lib\site-packages\tinyWinToast\tinyWinToast.py", line 560, in show
    subprocess.run(["PowerShell", "-ExecutionPolicy", "Bypass", "-File", path + "toast.ps1"])
AttributeError: 'module' object has no attribute 'run'
```

on Python 2.7.15

Version installed is tinyWinToast-1.1
Windows 10, version 1809

**Comment by Louie-v** [comment]
on Python 2.7.15
subprocess has no attribute 'run'，named 'call'，you should modify the tinyWinToast source file

on Python 3.6.8 & 3.7.2
use:
`from tinyWinToast.tinyWinToast import Toast`

but it not work on my computer,there is no errors and no toast.     -_-

**Comment by Louie-v** [comment]
> Trying to run `tinyWinToast/test/test.py` results in:
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 4, in <module>
>     toast = Toast()
> NameError: name 'Toast' is not defined
> ```
> 
> on Python 3.6.8 & 3.7.2
> 
> and:
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 1, in <module>
>     import tinyWinToast.tinyWinToast
>   File "C:\Python27\lib\site-packages\tinyWinToast\tinyWinToast.py", line 677, in <module>
>     toast.show()
>   File "C:\Python27\lib\site-packages\tinyWinToast\tinyWinToast.py", line 560, in show
>     subprocess.run(["PowerShell", "-ExecutionPolicy", "Bypass", "-File", path + "toast.ps1"])
> AttributeError: 'module' object has no attribute 'run'
> ```
> 
> on Python 2.7.15
> 
> Version installed is tinyWinToast-1.1
> Windows 10, version 1809

on Python 2.7.15
subprocess has no attribute 'run'，named 'call'，you should modify the tinyWinToast source file

on Python 3.6.8 & 3.7.2
use:
from tinyWinToast.tinyWinToast import Toast

but it not work on my computer,there is no errors and no toast. -_-

**Comment by J-CITY** [comment]
Hello! Sorry for the waiting. I think I found a error. Try to upgrade. If this does not help, try using a script from github. (Maybe I made some mistake in pip package. ¯ \ _ (ツ) _ / ¯)
